
spring:
  datasource:
    username: root
    password: itcast
    url: jdbc:mysql://localhost:3306/subway?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
